name: CI

on: [push]  #,pull_request

jobs:
  build:
    env:
      PIPENV_NO_INHERIT: 1
      PIPENV_IGNORE_VIRTUALENVS: 1
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11.5
        env:
          POSTGRES_USER: pythonpro
          POSTGRES_PASSWORD: pythonpro
          POSTGRES_DB: cursodjango
        ports: ['5434:5432']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install pipenv
        pipenv sync --dev
        cp contrib/env-sample .env

    - name: Lint with flake8
      run: |
        pipenv run flake8 .

    - name: Test with pytest
      run: |
        pipenv run pytest --cov=pypro

    - name: Posting Coverage
      run: |
        pipenv run codecov

